"""
Predefined investment strategy bundles.
Add new strategies here; the API and UI pick them up automatically.
"""

STRATEGIES: dict = {
    # ── 코스톨라니 달걀모형 ─────────────────────────────────────
    "kost_A": {
        "name": "코스톨라니 A단계",
        "subtitle": "저점 매집",
        "description": "경기침체 바닥, 비관론 극대. 전문가만 매수. 배당주·가치주 매집 시기.",
        "phase": "A",
        "group": "kostolany",
        "conditions": [
            {"field": "per",       "op": "<",  "value": 15},
            {"field": "pbr",       "op": "<",  "value": 1.5},
            {"field": "div_yield", "op": ">",  "value": 0.02},
        ],
        "logic": "AND",
        "color": "#22c55e",
    },
    "kost_B": {
        "name": "코스톨라니 B단계",
        "subtitle": "상승 추세",
        "description": "경기회복, 주가 완만히 상승. 일반 투자자 참여 시작. 성장주·경기민감주.",
        "phase": "B",
        "group": "kostolany",
        "conditions": [
            {"field": "roe",        "op": ">",  "value": 0.15},
            {"field": "change_pct", "op": ">",  "value": 0},
        ],
        "logic": "AND",
        "color": "#3fb950",
    },
    "kost_C": {
        "name": "코스톨라니 C단계",
        "subtitle": "고점 과열",
        "description": "과열·버블. 모두가 낙관. 주식 비중 축소, 현금·채권 확보 시기.",
        "phase": "C",
        "group": "kostolany",
        "conditions": [
            {"field": "per",        "op": ">",  "value": 30},
            {"field": "change_pct", "op": ">",  "value": 5},
        ],
        "logic": "AND",
        "color": "#f85149",
    },
    "kost_D": {
        "name": "코스톨라니 D단계",
        "subtitle": "고점 분산",
        "description": "주가 하락 시작. 기관 물량 분산. 방어주·배당주로 이동.",
        "phase": "D",
        "group": "kostolany",
        "conditions": [
            {"field": "div_yield", "op": ">",  "value": 0.025},
            {"field": "pbr",       "op": "<",  "value": 2},
        ],
        "logic": "AND",
        "color": "#d29922",
    },
    "kost_E": {
        "name": "코스톨라니 E단계",
        "subtitle": "하락 추세",
        "description": "경기침체 진입, 실적 악화. 방어 섹터, 채권 대안 배당주.",
        "phase": "E",
        "group": "kostolany",
        "conditions": [
            {"field": "div_yield", "op": ">",  "value": 0.03},
            {"field": "pbr",       "op": "<",  "value": 1.5},
        ],
        "logic": "AND",
        "color": "#f85149",
    },
    "kost_F": {
        "name": "코스톨라니 F단계",
        "subtitle": "저점 공포",
        "description": "공포·패닉 극대. 주가 과매도. 가치주 분할 매수 재개 타이밍.",
        "phase": "F",
        "group": "kostolany",
        "conditions": [
            {"field": "per", "op": "<",  "value": 12},
            {"field": "pbr", "op": "<",  "value": 1.2},
        ],
        "logic": "AND",
        "color": "#58a6ff",
    },

    # ── 전통 투자 전략 ───────────────────────────────────────────
    "value": {
        "name": "가치투자",
        "subtitle": "저평가 발굴",
        "description": "벤저민 그레이엄 스타일. 내재가치 대비 싼 주식. PER·PBR 낮고 배당 있음.",
        "group": "classic",
        "conditions": [
            {"field": "per", "op": "<",  "value": 15},
            {"field": "pbr", "op": "<",  "value": 1.5},
            {"field": "roe", "op": ">",  "value": 0.08},
        ],
        "logic": "AND",
        "color": "#58a6ff",
    },
    "dividend": {
        "name": "배당투자",
        "subtitle": "고배당 인컴",
        "description": "현금흐름 중심. 매년 배당으로 인컴 확보. 방어적 장기 보유.",
        "group": "classic",
        "conditions": [
            {"field": "div_yield", "op": ">",  "value": 0.025},
            {"field": "per",       "op": "<",  "value": 25},
        ],
        "logic": "AND",
        "color": "#3fb950",
    },
    "growth": {
        "name": "성장투자",
        "subtitle": "고ROE 성장주",
        "description": "피터 린치·필립 피셔 스타일. 높은 자기자본이익률로 빠른 성장.",
        "group": "classic",
        "conditions": [
            {"field": "roe",        "op": ">",  "value": 0.20},
            {"field": "change_pct", "op": ">",  "value": 0},
        ],
        "logic": "AND",
        "color": "#bc8cff",
    },
    "quality": {
        "name": "퀄리티투자",
        "subtitle": "우량주 집중",
        "description": "워런 버핏 스타일. 좋은 기업을 적정 가격에. ROE 높고 PER 합리적.",
        "group": "classic",
        "conditions": [
            {"field": "roe", "op": ">",  "value": 0.15},
            {"field": "per", "op": "<",  "value": 25},
            {"field": "pbr", "op": "<",  "value": 5},
        ],
        "logic": "AND",
        "color": "#d4a843",
    },
    "momentum": {
        "name": "모멘텀투자",
        "subtitle": "상승 추세 추종",
        "description": "오늘 오르는 종목이 내일도 오른다. 52W 고가 근처 강세 종목.",
        "group": "classic",
        "conditions": [
            {"field": "change_pct", "op": ">",  "value": 1},
        ],
        "logic": "AND",
        "color": "#f85149",
    },
    "deep_value": {
        "name": "역발상투자",
        "subtitle": "과매도 역투자",
        "description": "공포에 사고 탐욕에 판다. 52W 저점 근처 낙폭 과대 종목 발굴.",
        "group": "classic",
        "conditions": [
            {"field": "change_pct", "op": "<",  "value": -5},
            {"field": "per",        "op": "<",  "value": 20},
        ],
        "logic": "AND",
        "color": "#58a6ff",
    },

    # ── 전설적 투자자 전략 ────────────────────────────────────────
    "greenblatt": {
        "name": "그린블라트 마법공식",
        "subtitle": "이익수익률 + 자본수익률",
        "description": "조엘 그린블라트의 Magic Formula. 높은 자본수익률(ROE)과 낮은 PER 조합. 우량주를 저렴하게 사는 퀀트 전략.",
        "group": "legendary",
        "investor": "Joel Greenblatt",
        "conditions": [
            {"field": "per", "op": "<",  "value": 15},
            {"field": "roe", "op": ">",  "value": 0.25},
        ],
        "logic": "AND",
        "color": "#f0883e",
    },
    "neff": {
        "name": "존 네프 저PER",
        "subtitle": "배당 + 저평가",
        "description": "윈저 펀드의 존 네프 스타일. 극단적 저PER과 안정적 배당의 조합. 시장이 외면한 저평가 우량주.",
        "group": "legendary",
        "investor": "John Neff",
        "conditions": [
            {"field": "per",       "op": "<",  "value": 10},
            {"field": "div_yield", "op": ">",  "value": 0.02},
            {"field": "roe",       "op": ">",  "value": 0.10},
        ],
        "logic": "AND",
        "color": "#3fb950",
    },
    "schloss": {
        "name": "월터 슐로스 딥밸류",
        "subtitle": "순자산 이하 매수",
        "description": "벤저민 그레이엄의 수제자 월터 슐로스. PBR 1 미만 극단적 저평가 + 배당 기업만. 50년간 연 20% 수익.",
        "group": "legendary",
        "investor": "Walter Schloss",
        "conditions": [
            {"field": "pbr",       "op": "<",  "value": 1.0},
            {"field": "div_yield", "op": ">",  "value": 0.005},
        ],
        "logic": "AND",
        "color": "#58a6ff",
    },
    "lynch_garp": {
        "name": "피터 린치 GARP",
        "subtitle": "합리적 가격의 성장주",
        "description": "Growth At Reasonable Price. 피터 린치가 마젤란 펀드에서 사용한 전략. PER 대비 성장성이 뒷받침되는 종목.",
        "group": "legendary",
        "investor": "Peter Lynch",
        "conditions": [
            {"field": "per",        "op": "<",  "value": 20},
            {"field": "roe",        "op": ">",  "value": 0.15},
            {"field": "change_pct", "op": ">",  "value": 0},
        ],
        "logic": "AND",
        "color": "#bc8cff",
    },
    "dalio_allweather": {
        "name": "레이 달리오 올웨더",
        "subtitle": "경기 사이클 방어형",
        "description": "브리지워터의 레이 달리오 변형 전략. 어떤 경기 국면에서도 버티는 배당·가치 혼합. 안정성 최우선.",
        "group": "legendary",
        "investor": "Ray Dalio",
        "conditions": [
            {"field": "div_yield", "op": ">",  "value": 0.02},
            {"field": "pbr",       "op": "<",  "value": 3.0},
            {"field": "roe",       "op": ">",  "value": 0.08},
        ],
        "logic": "AND",
        "color": "#d29922",
    },
    "dreman_contrarian": {
        "name": "드레먼 역발상",
        "subtitle": "저PER 역발상 매수",
        "description": "데이비드 드레먼의 Contrarian 전략. 시장이 과도하게 비관적인 저PER·저PBR 종목에 집중. 군중 심리 역이용.",
        "group": "legendary",
        "investor": "David Dreman",
        "conditions": [
            {"field": "per",       "op": "<",  "value": 12},
            {"field": "pbr",       "op": "<",  "value": 1.5},
            {"field": "div_yield", "op": ">",  "value": 0.015},
        ],
        "logic": "AND",
        "color": "#f85149",
    },
    "marks_safety": {
        "name": "하워드 막스 안전마진",
        "subtitle": "리스크 우선 가치투자",
        "description": "오크트리의 하워드 막스 철학. 손실 회피를 최우선으로. PBR 1 미만이면서 수익성이 검증된 종목만.",
        "group": "legendary",
        "investor": "Howard Marks",
        "conditions": [
            {"field": "pbr", "op": "<",  "value": 1.0},
            {"field": "roe", "op": ">",  "value": 0.10},
        ],
        "logic": "AND",
        "color": "#58a6ff",
    },
    "templeton_global": {
        "name": "템플턴 글로벌가치",
        "subtitle": "극단적 비관 속 저평가",
        "description": "존 템플턴 경의 전략. '최대 비관의 시점이 최고 매수 시점'. 전 세계에서 가장 저렴한 우량주 발굴.",
        "group": "legendary",
        "investor": "John Templeton",
        "conditions": [
            {"field": "per",       "op": "<",  "value": 10},
            {"field": "pbr",       "op": "<",  "value": 1.2},
            {"field": "change_pct","op": "<",  "value": -3},
        ],
        "logic": "AND",
        "color": "#22c55e",
    },
}
