-- 스키마 생성
CREATE SCHEMA IF NOT EXISTS moodbite;
CREATE SCHEMA IF NOT EXISTS trend;
CREATE SCHEMA IF NOT EXISTS blog;
CREATE SCHEMA IF NOT EXISTS playground;

-- 기본 권한 설정
GRANT ALL PRIVILEGES ON SCHEMA moodbite TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA trend TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA blog TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA playground TO postgres;