name: Deploy Frontend to Vercel

on:
  push:
    branches: [ main ]
    paths:
      - 'moodbite/MoodBite_FE/**'
      - 'playground/fe/**'

jobs:
  deploy-moodbite:
    if: contains(github.event.head_commit.modified, 'moodbite/MoodBite_FE')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Deploy MoodBite to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN_MOODBITE }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID_MOODBITE }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_MOODBITE }}
        working-directory: ./moodbite/MoodBite_FE

  deploy-playground:
    if: contains(github.event.head_commit.modified, 'playground/fe')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Deploy PlayGround to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN_PLAYGROUND }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID_PLAYGROUND }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_PLAYGROUND }}
        working-directory: ./playground/fe